from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / 'output'
DOCS = ROOT / 'docs'
WIDTH, HEIGHT = 540, 960
MIN_TARGET = 66  # 44 screen pixels at a 360-pixel page width.
YEARS = (2026, 2027, 2028)
MONTHS = ('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC')
MONTH_NAMES = ('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December')
FONT_FILES = {'Body': 'calibri.ttf', 'Bold': 'calibrib.ttf', 'Editorial': 'georgia.ttf'}

# These are publishing inventories, not claims that Phase 1 renders every page.
MODULES = {
    'life': ('LIFESTYLE', 'DREAM LIFE|VISION BOARD|BUCKET LIST|WISHLIST|FAVORITE QUOTES|DREAM JOURNAL|BOOK LOG|READING LIST|MOVIE LOG|WATCHLIST|PODCASTS|GROCERY LIST|PARCEL TRACKER|PACKING CHECKLIST|TRIP PLANNER|TRIP ITINERARY|BIRTHDAYS|CONTACTS|CLEANING PLANNER|HOME PROJECTS'),
    'wellness': ('WELLNESS', 'WHEEL OF LIFE|MOOD TRACKER|ENERGY TRACKER|SLEEP TRACKER|HYDRATION|STEPS|MOVEMENT PLAN|DAILY WORKOUT|WEEKLY WORKOUT|CARDIO TRACKER|STRENGTH TRACKER|RUNNING LOG|MEAL PLANNER|MEAL IDEAS|NUTRITION LOG|PANTRY INVENTORY|RECIPES|WELLNESS ROUTINES'),
    'selfcare': ('SELF-CARE', 'SELF-CARE IDEAS|SELF-CARE JAR|30 DAY SELF-CARE|MINDFUL MOMENTS|POSITIVE THINKING|SELF-COMPASSION|REFLECTION|LETTER TO FUTURE SELF|STRESS LOG|AFFIRMATIONS|5 MINUTE JOURNAL|DAILY GRATITUDE|WEEKLY GRATITUDE|GRATITUDE BANK|GRATITUDE LETTER'),
    'productivity': ('PRODUCTIVITY', 'LONG TERM GOALS|SMART GOALS|PROJECT PLANNER|30 DAY CHALLENGE|ROUTINE PLANNER|PRIORITY MATRIX|TIME TRACKER|MEETING NOTES|APPOINTMENTS|TO DO LIST|DAILY TO DO|MONTHLY HABITS|PROJECT TRACKER|BRAIN DUMP|FOCUS SESSION'),
    'money': ('MONEY', 'YEARLY FINANCIAL OVERVIEW|FINANCIAL GOALS|BANK ACCOUNTS|SAVINGS ACCOUNTS|INCOME TRACKER|EXPENSE TRACKER|UPCOMING EXPENSES|MONTHLY BUDGET|WEEKLY BUDGET|SUBSCRIPTIONS|BILLS|INVESTMENT TRACKER|SINKING FUNDS|EMERGENCY FUND|DEBT TRACKER|SAVINGS TRACKER|52 WEEK SAVINGS CHALLENGE|ENVELOPE CHALLENGE|HOME SAVINGS|TRAVEL SAVINGS'),
    'notes': ('NOTES', 'LINED|GRID|DOT GRID|BLANK|CORNELL|STUDY NOTES|MEETING NOTES|PROJECT NOTES|BRAINSTORM|CHECKLIST'),
}
ANNUAL_TEMPLATES = 'YEAR OVERVIEW|YEAR AT A GLANCE|IMPORTANT DATES|YEARLY GOALS|QUARTER 1|QUARTER 2|QUARTER 3|QUARTER 4|VISION FOR THE YEAR|BIRTHDAYS|PROJECTS|FINANCIAL GOALS|PERSONAL GOALS|WELLNESS GOALS|CAREER / BUSINESS GOALS|YEAR-END REFLECTION'.split('|')
MONTHLY_TEMPLATES = 'MONTHLY DASHBOARD|MONTHLY CALENDAR|MONTHLY GOALS|MONTHLY PRIORITIES|MONTHLY HABITS|MONTHLY FINANCE SNAPSHOT|MONTHLY REFLECTION'.split('|')
NOTEBOOK_TYPES = ('LINED', 'DOT GRID', 'GRID', 'BLANK', 'STUDY', 'PROJECT')
STICKER_CATEGORIES = 'FUNCTIONAL|DATES|MONTHS|WEEKDAYS|NUMBERS|CHECKBOXES|FLAGS|LABELS|ARROWS|PRIORITIES|WORK|STUDY|MONEY|SAVINGS|BILLS|SHOPPING|FOOD|FITNESS|WELLNESS|SELF CARE|HOME|TRAVEL|READING|APPOINTMENTS|BIRTHDAYS|WEATHER|MOOD|DECORATIVE'.split('|')
COVER_CATEGORIES = ('MINIMAL', 'PASTEL', 'ABSTRACT', 'BOTANICAL', 'CELESTIAL', 'GEOMETRIC', 'TYPOGRAPHIC', 'SOFT LUXURY')
